sonar.organization=ghost-assembly
sonar.sources=.
sonar.tests=template/tests
sonar.exclusions=template/tests/**,node_modules/**,coverage/**,test-results/**,playwright-report/**,.scannerwork/**
sonar.qualitygate.wait=true
sonar.python.coverage.reportPaths=coverage/python.xml
sonar.qualitygate.timeout=600
